name: Fetch MLB Betting Odds

on:
  schedule:
    - cron: '0 12,14,16,18,20,22 * * *'  # Runs every 2 hours from 8AM–6PM ET
  workflow_dispatch:

jobs:
  fetch-betting-odds:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests supabase

      - name: Run betting odds fetch script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_KEY }}
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
        run: python fetch_betting_odds.py

