name: Fetch Pitcher Stats Daily

on:
  schedule:
    - cron: '00 13 * * *'  # 9:00 AM ET
    - cron: '30 15 * * *'  # 11:30 AM ET
    - cron: '30 16 * * *'  # 12:30 PM ET
    - cron: '00 18 * * *'  # 2:00 PM ET
    - cron: '30 20 * * *'  # 4:30 PM ET
    - cron: '00 22 * * *'  # 6:00 PM ET
  workflow_dispatch:


jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests supabase

    - name: Run pitcher stats script
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: python fetch_pitcher_stats.py
