name: Run DraftKings Lines Scraper

on:
  schedule:
    - cron: '0 12 * * *'  # 8am EST
    - cron: '0 14 * * *'  # 10am EST
    - cron: '0 16 * * *'  # 12pm EST
    - cron: '0 18 * * *'  # 2pm EST
    - cron: '0 20 * * *'  # 4pm EST
    - cron: '0 22 * * *'  # 6pm EST
    - cron: '0 0 * * *'   # 8pm EST
    - cron: '0 2 * * *'   # 10pm EST
  workflow_dispatch:

jobs:
  run-draftkings-lines:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas selenium beautifulsoup4 supabase regex webdriver-manager

      - name: Install Chrome
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable

      - name: Run script
        run: python draftkings_lines.py

