name: Run DraftKings Lines Script Every 2 Hours

on:
  schedule:
    - cron: '0 12 * * *'  # 8am ET
    - cron: '0 14 * * *'  # 10am ET
    - cron: '0 16 * * *'  # 12pm ET
    - cron: '0 18 * * *'  # 2pm ET
    - cron: '0 20 * * *'  # 4pm ET
    - cron: '0 22 * * *'  # 6pm ET
    - cron: '0 0 * * *'   # 8pm ET
    - cron: '0 2 * * *'   # 10pm ET
  workflow_dispatch:

jobs:
  run-draftkings-lines:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas supabase lxml regex


      - name: Run draftkings_lines.py
        run: python draftkings_lines.py
