name: 🔄 Update OU Result From Training Data

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["🕕 Daily TeamRankings Scraper"]
    types:
      - completed

jobs:
  update-ou-result:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install supabase

    - name: Run OU result update script
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: python update_ou_result_batch.py
