name: 📊 Update Series Over/Under Counts

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["🔄 Update OU Result From Training Data"]
    types:
      - completed

jobs:
  update-series:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Supabase client
      run: pip install supabase

    - name: Run update_series_results.py
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: python update_series_results.py
